### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by nmggithub** [angryziber/ipscan#26]
Exception in thread "main" java.lang.UnsatisfiedLinkError: /opt/jdk1.8.0_25/jre/lib/i386/libawt_xawt.so: libXext.so.6: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1814)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1083)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1835)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at java.awt.Toolkit$3.run(Toolkit.java:1636)
	at java.awt.Toolkit$3.run(Toolkit.java:1634)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1668)
	at java.awt.Component.<clinit>(Component.java:593)
	at net.azib.ipscan.Main.main(Main.java:95)

I do have the libXext.so.6 file. How do I get Java to see it?

**Comment by angryziber** [comment]
This is not a problem with ipscan, but with java.
Which distro do you have?

**Comment by nmggithub** [comment]
Wow, blast from the past. I reinstalled my distro and it fixed it.
