### ISSUE TITLE
All hosts display as alive

### ISSUE THREAD

**Issue by jstipe** [angryziber/ipscan#43]
Mac OS X 10.10.5 IP Scanner 3.2.1

When I scan with combined method, all IPs return as alive. No other scanners work. Happens on latest version as well.

How do I fix it?

Thanks!

**Comment by angryziber** [comment]
Please use the latest version 3.3.3 and try UDP and TCP pingers separately.
Which one works?

Do you have an unusual network configuration, socks proxy or something
simular?

**Comment by jstipe** [comment]
Running version 3.3.3:

Scanned 172.22.1.0/24, subnet I am in:

UDP returned no hosts

TCP returned 254 hosts

Probably have less than 20 hosts on the network.

No unusual network configuration. No proxies enabled.

Currently connected to home network behind Netgear N600 router. Same
behavior on work network connected to Cisco access layer and backbone
network devices through Cisco Wireless Access Point.

John Stipe
317-430-1532
jjstipe@gmail.com

**Comment by jstipe** [comment]
I scanned at work this morning in case it might be something on my home network. See attached. 508 hosts returned as alive. There are probably less than a dozen on this network.
<img width="712" alt="screen shot 2015-08-31 at 8 23 55 am" src="https://cloud.githubusercontent.com/assets/14029748/9578665/fb057558-4fb9-11e5-9866-c6ee8aea3d25.png">

**Comment by jstipe** [comment]
Do you have any suggestions? The tool is not very useful to me if it returns dead hosts as alive.

**Comment by jstipe** [comment]
Downloaded version 3.4. Issue persists

**Comment by medved-nsk** [comment]
The only thing I can suppose there is a gateway/router which answer with non-used IPs.
The first thing which worth to be checked are the MAC addresses of these IPs.
I'm not familar with MacOS but since its bsd-kernel based then 'arp -na' should help.

**Comment by le-jawa** [comment]
I'm seeing the exact same issue with 3.4.1.  On a Windows box on the same subnet, AngryIP works as expected.  From a Mac (OS X 10.10.5), I see the following issues:

- Results are inconsistent.  Sometimes, a few hosts will show up as dead (but not nearly all of them), but most of the time, all hosts show up as alive (blue dot, not green).
- The totals that get tallied at the end are not only off, but impossible (for example, 437/254 hosts alive).  Again, this number varies with each scan.
- A straight UDP scan returns no hosts alive.  TCP returns all hosts alive.
- Again, this works fine on the same subnets with the Windows version, so I don't see it being a router/switch issue.
- JRE on the Mac is version 1.8.91.

Thanks for looking at this, and let me know if you need additional info.

**Comment by tuksaur** [comment]
seeing same behavior. no amount of reinstall resolves. TCP all hosts alive all the time; UDP no hosts alive. Only 20 actual hosts on network. 

Is there a configuration file that can be altered to correct this behavior? 

Angry IP v3.4.2; build date August 4, 2016. Running Mac OSX 10.11.6.

**Comment by angryziber** [comment]
No idea yet of what might be the cause, but have any of you tried using
TCP/UDP/Combined pingers on Windows on the same subnet? Windows version
uses a different pinging method by default provided by the OS. Also, if you
can, please provide a dump of packets during the scan using either
Wireshark or tcpdump

**Comment by tuksaur** [comment]
my windows 7 vm scans just fine. expected results. but i dont want to have to run my vm every time i need to do a network scan. OS X used to work just fine.

dump file attached from OS X scan (all hosts alive).

[DumpFile01.pcap.zip](https://github.com/angryziber/ipscan/files/425365/DumpFile01.pcap.zip)

**Comment by angryziber** [comment]
Thanks for the quick dump, I will analyze it. Which Pinger did you use, the
default Combined one?
Also, what happens if you use the same Pinger in Windows?

**Comment by tuksaur** [comment]
ya no problem. thanks for putting a second set of eyes on it. I tried both TCP and TCP+UDP, same results in OSX. in Windows it gives expected/correct results. red icon for dead host, blue for alive (no greens; although only pinging for response and not for ports). OS X reports all 255 range as 'blue' or 'alive' for both Pinger types.

**Comment by angryziber** [comment]
The dump doesn't show anything unusual.
[Here is a debug build for OS X](https://github.com/angryziber/ipscan/files/425684/ipscan-mac-3.4.x-debug.zip)
Please run it from command-line, select TCP pinging method, scan and paste the output that you get on the console.

**Comment by tuksaur** [comment]
here is a TXT of the debug. again, 254/254 ping/alive.
[angry_debug.txt](https://github.com/angryziber/ipscan/files/425703/angry_debug.txt)

**Comment by angryziber** [comment]
Thanks, that means that sockets on your JVM behave erratically...
Let's have another try (with some of the optimization options removed)
[ipscan-mac-3.4.x-debug.zip](https://github.com/angryziber/ipscan/files/425743/ipscan-mac-3.4.x-debug.zip)

**Comment by tuksaur** [comment]
sorry, what do you mean w/o the optimization options? or is that change built into the debug you sent?

**Comment by angryziber** [comment]
Yes, that's built-in. Please run the scan and attach the log

**Comment by tuksaur** [comment]
new scan results.

[angry_debug.txt](https://github.com/angryziber/ipscan/files/425763/angry_debug.txt)

**Comment by angryziber** [comment]
OK, that didn't help. Another try please:
[ipscan-mac-3.4.x-debug.zip](https://github.com/angryziber/ipscan/files/425798/ipscan-mac-3.4.x-debug.zip)

**Comment by tuksaur** [comment]
unfortunately same results as before.

[angry_debug_v3.txt](https://github.com/angryziber/ipscan/files/425836/angry_debug_v3.txt)

**Comment by angryziber** [comment]
Thanks for trying, I am out of ideas for now.
Do you use the official Java from Oracle?

**Comment by angryziber** [comment]
I have tried Angry IP Scanner 3.4.2 on two diffierent Macs with older and latest Java (1.8 b101) and scanning worked properly...

Please try installing the latest official JVM from Oracle: http://java.com

**Comment by tuksaur** [comment]
how can i completely uninstall/remove angry IP scanner from my OS X system and try a reinstall? i have java up to date.

**Comment by le-jawa** [comment]
Angryziber,

Thanks for looking into this.  I did a clean install of AngryIP 3.4.2 (I believe it was clean, anyway) and updated my JDK to 1.8.0.u101.  Unfortunately, I'm still seeing the same problems; all hosts report alive, then the summary report shows an impossible number of live hosts (and it changes every scan).  Also, I've also got OS X upgraded and updated all the way (10.11.6)

Could we be running a newer version of OS X than you?

![screen shot 2016-08-22 at 14 06 58 -sans ip](https://cloud.githubusercontent.com/assets/19916394/17867279/cc91ebfc-6877-11e6-82d2-62fd2c81a121.png)

![screen shot 2016-08-22 at 14 28 52](https://cloud.githubusercontent.com/assets/19916394/17866534/de85589c-6874-11e6-923b-064f2b78d770.png)

**Comment by le-jawa** [comment]
tuksaur,

To answer your question to the best of my ability: Deleting the app itself should do it.  I looked in ~/Library/Application Support and didn't see a directory for AngryIP, so I presume there are no other files for it beyond the app package.  

I've been wrong before though...  ;-)

**Comment by tuksaur** [comment]
np. thank you. i’ll use my windows VM until i get the change to clean wipe my Mac and try to reinstall.
cheers,

**Comment by Fractal7** [comment]
Currently using the latest version of Angry IP scanner on mac and I am as well now dealing with this issue.

**Comment by le-jawa** [comment]
I _think_ I found the problem.  Here's what I get when I run AngryIP from the command line as root:

```
SEVERE: Unable to create pinger: pinger.icmp
<full trace removed for brevity>
Caused by: java.lang.RuntimeException: Unable to extract native library: rocksaw
	at net.azib.ipscan.core.LibraryLoader.loadLibrary(LibraryLoader.java:48)
	at org.savarese.rocksaw.net.RawSocket.<clinit>(RawSocket.java:82)
	... 19 more
Caused by: java.io.IOException: librocksaw.dylib not found in the jar file (classpath)
	at net.azib.ipscan.core.LibraryLoader.loadLibrary(LibraryLoader.java:34)
	... 20 more

```
Full stack trace attached.
[AnryIP Stack Trace.txt](https://github.com/angryip/ipscan/files/1576161/AnryIP.Stack.Trace.txt)
